application:
    message: Hello, %s! --- Configured by Spring Cloud Config Server
    external:
      service:
        endpoint: ${EXTERNAL_SERVICE_ENDPOINT}
        port: ${EXTERNAL_SERVICE_PORT}

spring:
  webflux:
    base-path: /greeting-external

feign:
  hystrix:
    enabled: true